In [2]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [3]:
from scipy.linalg import lu_factor
from scipy.linalg import lu_solve 


In [2]:
x = array([ 1.0000000000000001e-18, 1.0000000000000001e-18, 1.0000000000000001e-18, 1.0000000000000001e-18, 99999000.009999901, 99999998.00000003, 99999990.000000998, 1.0000000000000001e-18, 1.0000000000000001e-18, 1.0000000000000001e-18, 99990000.999900013, 1.0000000000000001e-18, 1.0000000000000001e-18, 1.0000000000000001e-18, 1.0000000000000001e-18, 99999666.667777792, 1.0000000000000001e-18, 1.0000000000000001e-18, 1.0000000000000001e-18, 1.0000000000000001e-18, 1.0000000000000001e-18, 1.0000000000000001e-18, 1.0000000000000001e-18, 1.0000000000000001e-18, 1.0000000000000001e-18, 1.0000000000000001e-18, 1.0000000000000001e-18, 1.0000000000000001e-18, 1.0000000000000001e-18, 1.0000000000000001e-18, 1.0000000000000001e-18, 1.0000000000000001e-18, 1.0000000000000001e-18, 0, 3.0139352459999907e-07, 99999000.009999901, 99999000.009999901])

In [3]:
x

array([  1.00000000e-18,   1.00000000e-18,   1.00000000e-18,
         1.00000000e-18,   9.99990000e+07,   9.99999980e+07,
         9.99999900e+07,   1.00000000e-18,   1.00000000e-18,
         1.00000000e-18,   9.99900010e+07,   1.00000000e-18,
         1.00000000e-18,   1.00000000e-18,   1.00000000e-18,
         9.99996667e+07,   1.00000000e-18,   1.00000000e-18,
         1.00000000e-18,   1.00000000e-18,   1.00000000e-18,
         1.00000000e-18,   1.00000000e-18,   1.00000000e-18,
         1.00000000e-18,   1.00000000e-18,   1.00000000e-18,
         1.00000000e-18,   1.00000000e-18,   1.00000000e-18,
         1.00000000e-18,   1.00000000e-18,   1.00000000e-18,
         0.00000000e+00,   3.01393525e-07,   9.99990000e+07,
         9.99990000e+07])

In [4]:
linalg.norm(x)

264570087.58101672

In [5]:
x.size

37

In [6]:
a = array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
lu = lu_factor(a)

In [11]:
lu

(array([[  7.00000000e+00,   8.00000000e+00,   9.00000000e+00],
        [  1.42857143e-01,   8.57142857e-01,   1.71428571e+00],
        [  5.71428571e-01,   5.00000000e-01,  -1.58603289e-16]]),
 array([2, 2, 2], dtype=int32))

In [14]:
b = array([1.,1.,1.])
dy = lu_solve(lu,b)

In [15]:
dy

array([ 0.2, -1.4,  1.2])

In [1]:
for k in range(4):
    print(k)
print(k)

0
1
2
3
3


In fortran 

do k = 1, 4
    print *, k
print *, k

1
2
3
4
5

In [4]:
k1 = [5.37587202e-018, 0.00000000e+000, 3.46931200e-011, 0.00000000e+000
 0.00000000e+000 3.46931200e-011 0.00000000e+000 5.12744408e-016
 0.00000000e+000 0.00000000e+000 0.00000000e+000 7.20000000e-015
 1.11730319e-015 0.00000000e+000 1.18538643e-017 3.07770287e-009
 2.47621006e-020 0.00000000e+000 6.00000000e-010 1.00653269e-022
 0.00000000e+000 0.00000000e+000 1.00000000e-040 2.06368821e-286
 8.86144152e-015 0.00000000e+000 9.35094757e-007 3.98107171e-009
 1.00000000e-008 0.00000000e+000 1.58113883e-006 1.00000000e-040
 2.74693948e-032 9.69860327e-032 1.21232541e-032 3.59409567e-011
 0.00000000e+000 0.00000000e+000 2.97812795e-011 0.00000000e+000
 0.00000000e+000 0.00000000e+000 3.89440874e-010 6.11881934e-020
 1.27493039e-014 6.36890260e-016 0.00000000e+000 4.90328670e-016
 0.00000000e+000 0.00000000e+000 0.00000000e+000 3.00000000e-010
 0.00000000e+000 1.60433445e-009 0.00000000e+000 4.39456043e-014
 2.25826451e-094 2.40000000e-010 2.06103101e-050 2.28148945e-015
 9.90568241e-115 2.20000000e-010 3.83423879e-022 2.55615919e-022
 5.01000000e-011 1.31989748e-270 3.00804650e-012 0.00000000e+000
 0.00000000e+000 1.04981722e-102 0.00000000e+000 3.22895989e-090
 0.00000000e+000 7.05076505e-011 0.00000000e+000 4.99700000e-011
 2.30193631e-016 0.00000000e+000 0.00000000e+000 0.00000000e+000
 1.49389160e-010 0.00000000e+000 0.00000000e+000 1.94140315e-009
 0.00000000e+000 2.40000000e-009 7.77871920e-010 5.78992764e-010
 3.07156986e-212 7.50000000e-010 1.20000000e-009 3.50000000e-010
 3.30755310e-317 1.60000000e-009 7.50000000e-010 0.00000000e+000
 2.50000000e-010 2.50000000e-010 4.80000000e-010 1.69000000e-009
 1.50000000e-009 1.17814375e-009 5.04918752e-010 0.00000000e+000
 2.27703051e-008 0.00000000e+000 1.37071244e-008 1.01000000e-009
 6.40000000e-010 0.00000000e+000 2.55096708e-008 1.80000000e-009
 0.00000000e+000 5.02717461e-009 2.40000000e-010 1.00000000e-011
 3.42000000e-010 4.53000000e-010 9.10000000e-010 5.20000000e-011
 5.20000000e-011 0.00000000e+000 2.46820357e-009 0.00000000e+000
 1.42084946e-010 1.10000000e-009 0.00000000e+000 7.27934152e-008
 0.00000000e+000 3.29737128e-008 7.59214880e-009 0.00000000e+000
 7.59214880e-009 0.00000000e+000 4.15094821e-009 0.00000000e+000
 4.15094821e-009 0.00000000e+000 1.60000000e-009 0.00000000e+000
 3.74511597e-008 0.00000000e+000 2.02236262e-008 0.00000000e+000
 4.20246022e-008 0.00000000e+000 7.56177422e-009 0.00000000e+000
 7.56177422e-009 0.00000000e+000 7.56177422e-009 2.00000000e-009
 3.30000000e-011 1.10000000e-009 7.66811581e-009 7.66811581e-016
 7.50000000e-010 1.25976188e-006 1.25976188e-006 1.25976188e-006
 1.37188880e-007 2.55616887e-007 3.83405790e-007 1.23138181e-006
 5.91063271e-007 3.10154295e-006 4.24484982e-007 1.06805899e-006
 1.09544512e-006 3.22373067e-008 2.13611797e-007 4.71041399e-007
 1.67055380e-006 1.41312420e-006 3.06724632e-008 5.91540362e-007
 3.29728980e-006 2.10872278e-006 1.78545695e-006 2.43369800e-006
 2.11625913e-007 3.30000000e-006 1.00000000e-009 1.00000000e-010
 5.00000000e-010 1.00000000e-013 5.00000000e-010 5.00000000e-010
 7.00000000e-010 7.00000000e-010 5.00000000e-010 0.00000000e+000
 1.00000000e-016 2.25000000e-015 1.00000000e-017 1.00000000e-017
 1.09544512e-006 3.22373067e-008 2.13611797e-007 4.71041399e-007
 1.67055380e-006 1.41312420e-006 3.06724632e-008 5.91540362e-007
 3.29728980e-006 2.10872278e-006 1.78545695e-006 2.43369800e-006
 2.11625913e-007 3.30000000e-006 1.00000000e-009 1.00000000e-010
 5.00000000e-010 1.00000000e-013 5.00000000e-010 5.00000000e-010
 7.00000000e-010 7.00000000e-010 5.00000000e-010 0.00000000e+000
 1.00000000e-016 2.25000000e-015 1.00000000e-017 1.00000000e-017
 1.31015916e-025 1.80275772e-088 4.87629899e-017 1.66882316e-015
 2.50000000e-018 0.00000000e+000 1.50000000e-015 3.60529886e-018
 2.27166610e-022 3.33356062e-014 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 4.60000000e-018 5.00000000e-018
 2.80000000e-017 5.00000000e-017 3.00000000e-017 2.37000000e-015
 1.00000000e-018 3.00000000e-021 9.30000000e-018 1.02000000e-014
 7.30000000e-015 7.50000000e-015 1.17000000e-015 5.10000000e-015
 5.00000000e-015 9.70000000e-015 4.21000000e-015 1.17000000e-014
 9.30000000e-018 7.53160725e-025 0.00000000e+000 1.31893384e-020
 0.00000000e+000 1.31893384e-018 0.00000000e+000 1.31893384e-018
 0.00000000e+000 7.84725900e-027 1.39184640e-024 1.66731600e-028]

SyntaxError: invalid syntax (<ipython-input-4-a13946398c3e>, line 1)